# MySQL. Versions 5.6.4 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") || "mariadb" %>

development:
  <<: *default
  database: epitrello

test:
  <<: *default
  database: epitrello_test
#
production:
  primary: &primary_production
    <<: *default
    database: epitrello_production
    username: epitrello
    password: <%= ENV["EPITRELLO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: epitrello_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: epitrello_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: epitrello_production_cable
    migrations_paths: db/cable_migrate
